const verses = [{script:"For the word of God is alive and active. - Hebrews 4:12"}, 
{script:"For the word of the Lord is right and true. - Psalm 33:4"},
{script:"Man shall not live on bread alone, but on every word that comes from the mouth of God. - Matthew 4:4"},
{script:"I have hidden your word in my heart that I might not sin against you. - Psalm 119:11"},
{script:"The words of the Lord are flawless.  Psalm 12:6"},
{script:"Heaven and earth will pass away but my words will never pass away.  - Matthew 24:35"},
{script:"Your word is a lamp for my feet and a light on my path. - Psalm 119:105"},
{script:"Then you will know the truth, and the truth will set you free. - John 8:32"},
{script:"Therefore everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock. - Matthew 7:24"},
{script:"I wait for the Lord, my soul waits, and in his word my whole being waits. - Psalm 130:5"},
{script:"Do not merely listen to the word, and so deceive yourselves.  Do what it says. - James 1:22"},
{script:"All scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness. - 2 Timothy 3:16"},
{script:"How can a young person stay on the path of purity? By living according to your word. - Psalm 119:9"},
{script:"Every word of God is flawless; he is a shield to those who take refuge in him. - Proverbs 30:5"},
{script:"The Lord is good to all. - Psalm 145:9"},
{script:"You are the God who sees. - Genesis 16:13"},
{script:"Do not be afraid for I am with you. - Isaiah 43:5"},
{script:"I am with you always. - Matthew 28:20"},
{script:"The LORD is good to all. - Psalm 145:9"},
{script:"The Lord bless you and keep you. - Numbers 6:24"},
{script:"The Lord gives wisdom. - Proverbs 2:6"},
{script:"In the beginning, God created the heavens and the earth. - Genesis 1:1"}, 
{script:"The heavens declare the glory of God. - Psalm 19:1"},
{script:"Jesus Christ is the same yesterday, today and forever. - Hebrews 13:8"},
{script:"The Lord will fight for you; you need only to be still. - Exodus 14:14"},
{script:"Every good gift and every perfect gift is from above. - James 1:17"},
{script:"God is our refuge and strength, an ever present in trouble. - Psalm 46:1"},
{script:"The same Lord is Lord of all and richly blesses all who call on him. - Romans 10:12"},
{script:"The Lord is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary, and his understanding no one can fathom. - Isaiah 40:28"},
{script:"He is not here, he is risen! - Matthew 28:6"},
{script:"Do not let your hearts be troubled. You believe in God; believe also in me. - John 14:1"},
{script:"I am the way and the truth and the life. No one comes to the Father except through me. - John 14:6"},
{script:"I and the Father are one. - John 10:30"},
{script:"Come, follow me, Jesus said, and I will send you out to fish for people. - Matthew 4:19"},
{script:"And surely I am with you always, to the very end of the age. - Matthew 28:20"},
{script:"In the same way, the Spirit helps us in our weakness. - Romans 8:26"},
{script:"Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom. - 2 Corinthians 3:17"},
{script:"But the Advocate, the Holy Spirit, whom the Father will send in my name, will teach you all things and will remind you of everything I have said to you. - John 14:26"},
{script:"The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full. - John 10:10"},
{script:"For God did not send his son into the world to condemn the world, but to save the world through him. - John 3:17"},
{script:"For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord. - Romans 6:23"},
{script:"But God demonstrates his own love for us in this: While we were yet still sinners, Christ died for us. - Romans 5:8"},
{script:"I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world. - John 16:33"},
{script:"But the fruit of the Spirit is love, joy, peace, forebearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law.  Galatians 5:22-23"},
{script:"Love one another. - 1 John 3:23"},
{script:"Pray continually. - 1 Thessalonians 5:17"},
{script:"I praise you because I am fearfully and wonderfully made. - Psalm 139:14"},
{script:"I can do all this through Him who gives me strength. - Philippians 4:13"},
{script:"Be still, and know that I am God. - Psalm 46:10"},
{script:"I will praise you, Lord, with all my heart. - Psalm 138:1"},
{script:"Trust in the Lord with all your heart. - Proverbs 3:5"},
{script:"Rejoice in the Lord always. I will say it again: Rejoice! - Philippians 4:4"},
{script:"The Lord has done it this very day; let us rejoice today and be glad. - Psalm 118:24"},
{script:"Give thanks to the Lord, for he is good. His love endures forever. - Psalm 136:1"},
{script:"Let everything that has breath praise the Lord. - Psalm 150:6"},
{script:"When I am afraid, I put my trust in You. - Psalm 56:3"},
{script:"Cast all your anxiety on him because he cares for you. - 1 Peter 5:7"},
{script:"You are the light of the world. - Matthew 5:14"},
{script:"Believe in the Lord Jesus Christ, and you will be saved. - Acts 16:31"},
{script:"This is love for God: to keep his commands. - 1 John 5:3"},
{script:"Fear God and keep his commandments. - Ecclesiastes 12:13"},
{script:"Whatever you do, do it all for the glory of God. - 1 Corinthians 10:31"},
{script:"We must obey God rather than human beings. - Acts 5:29"},
{script:"Trust in the Lord forever, for the Lord, the Lord himself, is the Rock eternal. - Isaiah 26:4"},
{script:"Be strong and courageous. Do not be afraid, do not be discouraged, for the Lord your God will be with you wherever you go. - Joshua 1:9"},
{script:"You shall love the Lord your God with all your heart and with all your soul and with all your strength. - Deuteronomy 6:5"},
{script:"Children, obey your parents in the Lord, for this is right. Honor your father and mother which is the first commandment with a promise. - Ephesians 6:1"},
{script:"If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness. - 1 John 1:9"},
{script:"Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver. - 2 Corinthians 9:7"},
{script:"You dear children, are from God and have overcome them, because the One who is in you is greater than the one who is in the world. - 1 John 4:4"},
{script:"For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline. - 2 Timothy 1:7"},
{script:"Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you. - Ephesians 4:32"},
{script:"We love because He first loved us. -1 John 4:19"},
{script:"Children, obey your parents in everything. - Colossians 3:20"},
{script:"Love your neighbor as yourself. - Matthew 22:39"},
{script:"An honest witness does not deceive, but a false witness pours out lies. - Proverbs 14:5"},
{script:"Do not judge, or you too will be judged. - Matthew 7:1"},
{script:"Set your minds on things above, not on earthly things. - Colossians 3:2"},
{script:"Let the message of Christ dwell in you richly. - Colossians 3:16"},
{script:"Everyone who calls on the name of the Lord will be saved. - Romans 10:13"},
{script:"For all have sinned and fall short of the glory of God. - Romans 3:23"},
{script:"Do to others as you would have them do to you. - Luke 6:31"},
{script:"Do not be misled: Bad company corrupts good character. - 1 Corinthians 15:33"},
{script:"No one can serve two masters. - Matthew 6:24"},
{script:"Walk with the wise and become wise, for a companion of fools suffers harm. - Proverbs 13:20"},
{script:"Be joyful in hope, patient in affliction, faithful in prayer. - Romans 12:12"},
{script:"Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you. - Ephesians 4:32"},
{script:"So we fix our eyes not on what is seen, but on what is unseen. For what is seen is temporary, but what is unseen is eternal. - 2 Corinthians 4:18"},
{script:"Do not be deceived: God cannot be mocked. A man reaps what he sows. - Galatians 6:7"},
{script:"Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up according to their needs, that it may benefit those who listen.  Ephesians 4:29"},  
{script:"For the Lord watches over the way of the righteous, but the way of the wicked leads to destruction. - Psalm 1:6"},
{script:"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God which transcends all understanding will guard your hearts and your minds in Christ Jesus. - Philippians 4:6-7"},
{script:"Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own. - Matthew 6:34"},
{script:"The Character and Abilities of God - Isaiah 40:13-31"},
{script:"The 10 Commandments - Exodus 20:1-17"},
{script:"The Greatest Commandment - Matthew 22:37-40"},
{script:"The Lord is Our Shepherd - Psalm 23:1-6"},
{script:"The Lord s Prayer - Matthew 6:9-13"},
{script:"Suffering in Christ -  Romans 5:1-5"},
{script:"The Full Armor of God - Ephesians 6:13-18"},

];

module.exports = verses;

